kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ include "n8n.fullname" . }}-config
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
data:
  N8N_METRICS: {{ .Values.n8n.metrics | quote }}
  N8N_METRICS_PREFIX: n8n_