apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "actualbudget.fullname" . }}-server
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes: {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "actualbudget.fullname" . }}-user
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes: {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
