apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "music-graph-ui.fullname" . }}-config
  labels:
    {{- include "music-graph-ui.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}