apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}