apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
{{- if .Values.vaulwarden.databaseUrl }}
  DATABSE_URL: {{ .Values.vaulwarden.databaseUrl | b64enc }}
{{- end }}
{{- if .Values.vaulwarden.adminToken }}  
  ADMIN_TOKEN: {{ .Values.vaulwarden.adminToken | b64enc }}
{{- end }}