apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-config
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  docker.yaml: |
    ---
  {{- if .Values.config.services }}
  services.yaml: |
    {{- .Values.config.services | nindent 4 }}
  {{- end }}
  {{- if .Values.config.widgets }}
  widgets.yaml: |
    {{- .Values.config.widgets | nindent 4 }}
  {{- end }}
  {{- if .Values.config.settings }}
  settings.yaml: |
    {{- .Values.config.settings | nindent 4 }}
  {{- end }}
  {{- if .Values.config.bookmarks }}
  bookmarks.yaml: |
    {{- .Values.config.bookmarks | nindent 4 }}
  {{- end }}